name: Blobby
description: Bloby project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  im_stepper: ^0.1.3
  flutter_native_splash: ^2.1.1
  shared_preferences: any
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: adys
      fonts:
        - asset: fonts/ADYS-Regular-V5-4.ttf
        - asset: fonts/ADYS-Bold-V5-4.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#101010"
  image: "assets/logo.png"